### PR TITLE
There's an issue with the latest version of protagonist, so this make…

### PR DESCRIPTION
**Pull request by voor**
…s the version included in aglio exact.

### CODE REVIEW

**Comment by voor** [comment]
See apiaryio/protagonist#73

**Comment by voor** [comment]
@kylef Yes, the issue is still persisted on Linux:

```
➜  ~  npm install -g protagonist
npm http GET https://registry.npmjs.org/protagonist
npm http 200 https://registry.npmjs.org/protagonist
npm http GET https://registry.npmjs.org/protagonist/-/protagonist-1.2.0-beta.2.tgz
npm http 200 https://registry.npmjs.org/protagonist/-/protagonist-1.2.0-beta.2.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> protagonist@1.2.0-beta.2 install /home/voor/.npm/lib/node_modules/protagonist
> node-gyp rebuild

gyp: drafter/drafter.gyp not found (cwd: /home/voor/.npm/lib/node_modules/protagonist)
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.3-200.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/voor/.npm/lib/node_modules/protagonist
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by kylef** [comment]
@voor Just noticed the fix wasn't complete, working on making another fix.

I didn't realise NPM would install pre-releases by default with `^1.1.1`.

**Comment by voor** [comment]
Yeah, neither did I.  Seems odd that it would.

**Comment by pksunkara** [comment]
Thanks for the PR. This is going to be a temporary fix until the protagonist release is fixed.

**Pull request merged**
