### PR TITLE
Added Resource Attributes

### PR DESCRIPTION
**Pull request by Protossoario**
Modified the base template to add a table-like structure for the Attributes section of a Resource, if added.

### CODE REVIEW

**Comment by wyattjoh** [comment]
What's the ETA on this PR?

**Comment by danielgtaylor** [comment]
@wyattjoh I'm looking at it today, will try to get it in (maybe updated the example) and push a release if everything is good.

**Comment by danielgtaylor** [comment]
@Protossoario thanks for this pull request. I'm going to merge it in, but before doing another release I'd really like to 1. add support for attributes in more places and 2. support nested structures & arrays. Work is underway to make these a bit easier but it's probably still a couple weeks away from implementation.

**Comment by Protossoario** [comment]
@danielgtaylor yeah, I thought about adding support for nested structures, but couldn't figure out a quick way to present them neatly.

**Comment by danielgtaylor** [comment]
@Protossoario yeah, it's more difficult than it initially seems. I'm still working on a good presentation.

**Pull request merged**
