### PR TITLE
Compile to markdown when output is markdown file

### PR DESCRIPTION
**Pull request by maximeaubaret**
Render or compile to markdown depending on the output file extension.
See #115.

### CODE REVIEW

**Comment by danielgtaylor** [comment]
@maximeaubaret thanks this looks great. Any chance you could add a unit test to make sure it works as intended? That will prevent future changes from breaking things! :+1:

**Comment by maximeaubaret** [comment]
I'm on it ;)



—
Envoyé avec Mailbox

**Comment by danielgtaylor** [comment]
@maximeaubaret thanks, let me know if you need any help!

**Comment by maximeaubaret** [comment]
@danielgtaylor It's done :)

**Comment by danielgtaylor** [comment]
@maximeaubaret looks great! Thanks a lot for taking the time to write the tests! :+1:

**Comment by maximeaubaret** [comment]
Always a pleasure :+1:

**Comment by stygiansabyss** [comment]
Should this work with `-o output.md` as well?

**Pull request merged**
