### PR TITLE
Give credit for JSON schema generation to Drafter

### PR DESCRIPTION
**Pull request by alexturek**

### CODE REVIEW

**Comment by alexturek** [comment]
Hey Daniel, been a while!

I spent a couple hours going nuts trying to figure out how JSON schema (that I didn't write) was turning up in the Aglio documentation, and then I learned about Drafter...

Although now that I look in `package.json` I don't see it anywhere. How are those schemas getting into the docs?? (feel free to close this PR if it's not accurate)

**Comment by danielgtaylor** [comment]
@alexturek hey! Hope everything is going well. We should catch up some time!

How did you install Aglio? Are you using the new betas (via `npm install aglio@beta`) or the latest stable/normal release? The betas should be using Drafter while the normal release hasn't been updated to use it yet. If you're using the beta then I'll go ahead and update the README in the `theme-engine` branch :+1:

**Comment by alexturek** [comment]
Oh haha I should have checked the version, I didn't think the guy who set
it up for us was using a beta

Our version is `"aglio": "^2.0.0-beta1",`

**Comment by danielgtaylor** [comment]
@alexturek this is now up to date on the main readme after merging the theme engine branch onto master. Thanks!

**Pull request closed without merging**
